#pragma once
//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------


namespace Windows {
    namespace UI {
        namespace Xaml {
            namespace Controls {
                ref class Grid;
                ref class Image;
                ref class SplitView;
                ref class Button;
                ref class TextBlock;
                ref class ListBox;
            }
        }
    }
}

namespace VEELB
{
    [::Windows::Foundation::Metadata::WebHostHidden]
    partial ref class MainPage : public ::Windows::UI::Xaml::Controls::Page, 
        public ::Windows::UI::Xaml::Markup::IComponentConnector,
        public ::Windows::UI::Xaml::Markup::IComponentConnector2
    {
    public:
        void InitializeComponent();
        virtual void Connect(int connectionId, ::Platform::Object^ target);
        virtual ::Windows::UI::Xaml::Markup::IComponentConnector^ GetBindingConnector(int connectionId, ::Platform::Object^ target);
    
    private:
        bool _contentLoaded;
    
        private: ::Windows::UI::Xaml::Controls::Grid^ SplashScreenGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ MainGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ JobNumberGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ WebcamFeedGrid;
        private: ::Windows::UI::Xaml::Controls::Grid^ ScreenSaverGrid;
        private: ::Windows::UI::Xaml::Controls::Image^ screenSaverImg;
        private: ::Windows::UI::Xaml::Controls::SplitView^ WebcamSplitter;
        private: ::Windows::UI::Xaml::Controls::Image^ imgCV;
        private: ::Windows::UI::Xaml::Controls::Button^ exitWebcamBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ settingsWebcamBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ oneBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ twoBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ threeBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ fourBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ fiveBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ sixBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ sevenBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ eightBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ nineBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ zeroBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ backspaceBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ clearBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ returnBtn;
        private: ::Windows::UI::Xaml::Controls::Image^ returnImage;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ jobIdNumTxtBlock;
        private: ::Windows::UI::Xaml::Controls::TextBlock^ mainGridJobNumberTxtBlk;
        private: ::Windows::UI::Xaml::Controls::Button^ initBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ enterJobNumberBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ settingsrBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ toggleHistoryBtn;
        private: ::Windows::UI::Xaml::Controls::Grid^ historyGrid;
        private: ::Windows::UI::Xaml::Controls::ListBox^ ConsoleListBox;
        private: ::Windows::UI::Xaml::Controls::Button^ sleepBtn;
        private: ::Windows::UI::Xaml::Controls::Button^ startBtn;
    };
}

