//------------------------------------------------------------------------------
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//------------------------------------------------------------------------------
#include "pch.h"

#if defined _DEBUG && !defined DISABLE_XAML_GENERATED_BINDING_DEBUG_OUTPUT
extern "C" __declspec(dllimport) int __stdcall IsDebuggerPresent();
#endif

#include "MainPage.xaml.h"

void ::VEELB::MainPage::InitializeComponent()
{
    if (_contentLoaded)
    {
        return;
    }
    _contentLoaded = true;
    ::Windows::Foundation::Uri^ resourceLocator = ref new ::Windows::Foundation::Uri(L"ms-appx:///MainPage.xaml");
    ::Windows::UI::Xaml::Application::LoadComponent(this, resourceLocator, ::Windows::UI::Xaml::Controls::Primitives::ComponentResourceLocation::Application);
}

void ::VEELB::MainPage::Connect(int __connectionId, ::Platform::Object^ __target)
{
    switch (__connectionId)
    {
        case 1:
            {
                ::Windows::UI::Xaml::Controls::Page^ element1 = safe_cast<::Windows::UI::Xaml::Controls::Page^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Page^>(element1))->Loaded += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::Page_Loaded);
            }
            break;
        case 2:
            {
                this->SplashScreenGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 3:
            {
                this->MainGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 4:
            {
                this->JobNumberGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 5:
            {
                this->WebcamFeedGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 6:
            {
                this->ScreenSaverGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Grid^>(this->ScreenSaverGrid))->Tapped += ref new ::Windows::UI::Xaml::Input::TappedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::Input::TappedRoutedEventArgs^))&MainPage::ScreenSaverGrid_Tapped);
            }
            break;
        case 7:
            {
                this->screenSaverImg = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 8:
            {
                this->WebcamSplitter = safe_cast<::Windows::UI::Xaml::Controls::SplitView^>(__target);
            }
            break;
        case 9:
            {
                this->imgCV = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 10:
            {
                this->exitWebcamBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->exitWebcamBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::exitWebcamBtn_Click);
            }
            break;
        case 11:
            {
                this->settingsWebcamBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->settingsWebcamBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::settingsWebcamBtn_Click);
            }
            break;
        case 12:
            {
                this->oneBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->oneBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::oneBtn_Click);
            }
            break;
        case 13:
            {
                this->twoBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->twoBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::twoBtn_Click);
            }
            break;
        case 14:
            {
                this->threeBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->threeBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::threeBtn_Click);
            }
            break;
        case 15:
            {
                this->fourBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->fourBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::fourBtn_Click);
            }
            break;
        case 16:
            {
                this->fiveBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->fiveBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::fiveBtn_Click);
            }
            break;
        case 17:
            {
                this->sixBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->sixBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::sixBtn_Click);
            }
            break;
        case 18:
            {
                this->sevenBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->sevenBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::sevenBtn_Click);
            }
            break;
        case 19:
            {
                this->eightBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->eightBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::eightBtn_Click);
            }
            break;
        case 20:
            {
                this->nineBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->nineBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::nineBtn_Click);
            }
            break;
        case 21:
            {
                this->zeroBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->zeroBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::zeroBtn_Click);
            }
            break;
        case 22:
            {
                this->backspaceBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->backspaceBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::backspaceBtn_Click);
            }
            break;
        case 23:
            {
                this->clearBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->clearBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::clearBtn_Click);
            }
            break;
        case 24:
            {
                this->returnBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->returnBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::returnBtn_Click);
            }
            break;
        case 25:
            {
                this->returnImage = safe_cast<::Windows::UI::Xaml::Controls::Image^>(__target);
            }
            break;
        case 26:
            {
                this->jobIdNumTxtBlock = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 27:
            {
                this->mainGridJobNumberTxtBlk = safe_cast<::Windows::UI::Xaml::Controls::TextBlock^>(__target);
            }
            break;
        case 28:
            {
                this->initBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->initBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::initBtn_Click);
            }
            break;
        case 29:
            {
                this->enterJobNumberBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->enterJobNumberBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::enterJobNumberBtn_Click);
            }
            break;
        case 30:
            {
                this->settingsrBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
            }
            break;
        case 31:
            {
                this->toggleHistoryBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->toggleHistoryBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::toggleHistoryBtn_Click);
            }
            break;
        case 32:
            {
                this->historyGrid = safe_cast<::Windows::UI::Xaml::Controls::Grid^>(__target);
            }
            break;
        case 33:
            {
                this->ConsoleListBox = safe_cast<::Windows::UI::Xaml::Controls::ListBox^>(__target);
            }
            break;
        case 34:
            {
                this->sleepBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->sleepBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::sleepBtn_Click);
            }
            break;
        case 35:
            {
                this->startBtn = safe_cast<::Windows::UI::Xaml::Controls::Button^>(__target);
                (safe_cast<::Windows::UI::Xaml::Controls::Button^>(this->startBtn))->Click += ref new ::Windows::UI::Xaml::RoutedEventHandler(this, (void (::VEELB::MainPage::*)
                    (::Platform::Object^, ::Windows::UI::Xaml::RoutedEventArgs^))&MainPage::startBtn_Click);
            }
            break;
    }
    _contentLoaded = true;
}

::Windows::UI::Xaml::Markup::IComponentConnector^ ::VEELB::MainPage::GetBindingConnector(int __connectionId, ::Platform::Object^ __target)
{
    __connectionId;         // unreferenced
    __target;               // unreferenced
    return nullptr;
}


